document.addEventListener('DOMContentLoaded', function () {
    let blogPosts = [
        { title: "17 July 2024", content: "Following a successful presentation and demonstration of our project yesterday morning, we are proud to announce that we have won the 2024 IEEE AP-S Student Design Contest. We would like to express our gratitude to our mentor, Johan Lundgren, and our team member, Christian Nelson, for their invaluable support. Additionally, we extend our thanks to the EIT department at Lund University for their support throughout this project. Lastly, we sincerely thank the IEEE AP-S organization for believing in our proposal and providing the necessary funding to make our project a reality <img src='images/winners.jpg' class='blogpic' alt='nerds'> <img src='images/1st_place_new.jpg' class='blogpic' alt='nerds'>" },
        { title: "15 July 2024", content: "Today we finished up the last bit of testing before we took part of the conference opening cermony. After some intense days of final testing here in Florence it is finally time for us to present our project. Tomorrow morning between 09.30 and 12.00 will present the PICC to the judges and anyone interested at the conference. <img src='images/conference_group_pic.jpg' class='blogpic' alt='nerds'>" },
        { title: "13 July 2024", content: "Our team has successfully arrived in Florence. Despite some expected train issues on our way to Copenhagen Airport, we managed to catch our flight on time and arrived in Florence yesterday afternoon. After a brief sightseeing excursion and enjoying a delicious sandwich at All'Antico Vinaio, we called it a night after a long day of travel. Today, we focused on checking all components and began testing our equipment on Italian soil for the first time. Our official presentation at the conference is scheduled for Tuesday next week. In preparation, we will conduct extensive testing to ensure everything operates smoothly during our presentation. <img src='images/picc_box_florence.jpg' class='blogpic' alt='nerds'>" },
        { title: "8 July 2024", content: "Yesterday marked the one week notice for the start of the conference where we will finally be presenting the PICC. After handing in the project the 20th of May we took some well earned time off, before getting back at it last Wednesday when we tested everything and started planning our presentaion for the conference. This week comes down to the final planning for the conference before travelling down to Florence on Friday." },
        { title: "6 May 2024", content: "Today marked the 2 week notice for the project deadline. A lot has happened since the last post, we've kept on devolping the software, making big advancements with the signal processing and fixing bugs in the nanoVNA connection. There is still work to be done, both on the hardware and software side with some parts hopefully being delivered early this week." },
        { title: "5 April 2024", content: "Following a series of challenges in our software development, we achieved a notable milestone today by successfully establishing a connection with our nanoVNA. This progress hopefully marks a turning point in our software development efforts. With this breakthrough, we are optimistic about the path ahead, anticipating a smoother development process moving forward. After two days of hard work, the team will be taking a well-deserved break this weekend, recharging for next week. " },
        { title: "4 April 2024", content: "The development of hardware and software is progressing. Long nights and huge amounts of RedBull = impressive results! Looking forward to revealing our project this summer! <img src='images/hax.jpg' class='blogpic' alt='nerds'>" },
        { title: "9 Feb 2024", content: "We have started building the setup. We are also looking for sponsorships and grants to afford going to Florence and attend the conference. <img src='images/olhax.jpg' class='blogpic' alt='nerds'>" },
        { title: "8 Feb 2024", content: "We, The PICC Group from Lund University, are happy to announce that we have been selected as one of the 6 finalists in the IEEE AP-S Student design contest." },
        // Add more blog posts here
    ];

    let blogPostsContainer = document.getElementById('blogPosts');

    blogPosts.forEach(post => {
        let postElement = document.createElement('div');
        postElement.innerHTML = `<h3>${post.title}</h3><p>${post.content}</p>`;
        blogPostsContainer.appendChild(postElement);
    });
});
